### ISSUE TITLE
[Suggestion] Integrate with Github Actions

### ISSUE THREAD

**Issue by PDDStudio** [arconsis/measurements#33]
Hi again,

another small suggestion from my side would be to make use of [GitHub Actions](https://github.com/features/actions).  
We could use it to run tests/builds on new PRs and after merge requests to one of the target branches (e.g develop/master).  

Any thoughts on this or was this already proposed?

Regards,
Patrick

**Comment by c15yi** [comment]
I also thought of that already and would really like to use those.
I just didn't have the time to play around with it yet.

There are quite a few tests and all should run. If you want you could create some actions that are run on PRs.
