### ISSUE TITLE
null seafty

### ISSUE THREAD

**Issue by ChinmayaGit** [arconsis/measurements#39]
Having Null safety issue. Please fix it.
And This Error:-

Because no versions of firebase_database match >8.0.0 <8.0.1 and firebase_database >=8.0.1 <8.0.2 depends on firebase_database_platform_interface ^0.1.0+1, firebase_database >8.0.0 <8.0.2 requires firebase_database_platform_interface ^0.1.0+1.
And because firebase_database >=8.0.2 <8.1.0 depends on firebase_database_platform_interface ^0.1.0+2, firebase_database >8.0.0 <8.1.0 requires firebase_database_platform_interface ^0.1.0+1.
Because firebase_database >=8.1.0 <8.2.0 depends on firebase_database_platform_interface ^0.1.0+3 and firebase_database >=8.2.0 <9.0.0-dev.0 depends on firebase_database_platform_interface ^0.1.0+4, firebase_database >=8.1.0 <9.0.0-dev.0 requires firebase_database_platform_interface ^0.1.0+3.
Thus, firebase_database >8.0.0 <9.0.0-dev.0 requires firebase_database_platform_interface ^0.1.0+1.
And because firebase_database 8.0.0 depends on firebase_database_platform_interface ^0.1.0, firebase_database >=8.0.0 <9.0.0-dev.0 requires firebase_database_platform_interface ^0.1.0.
And because every version of firebase_database_platform_interface depends on plugin_platform_interface ^2.0.0 and path_provider_platform_interface <2.0.0-nullsafety depends on plugin_platform_interface ^1.0.1, firebase_database >=8.0.0 <9.0.0-dev.0 is incompatible with path_provider_platform_interface <2.0.0-nullsafety.
And because path_provider >=1.6.10 <2.0.0-nullsafety depends on path_provider_linux ^0.0.1 which depends on path_provider_platform_interface ^1.0.1, firebase_database >=8.0.0 <9.0.0-dev.0 is incompatible with path_provider >=1.6.10 <2.0.0-nullsafety.
So, because tact depends on both path_provider ^1.6.11 and firebase_database ^8.0.0, version solving failed.
pub get failed (1; So, because tact depends on both path_provider ^1.6.11 and firebase_database ^8.0.0, version solving failed.)

Thanks.

**Comment by c15yi** [comment]
This repository is no longer maintained and will be archived.

The code base is quite old (2 years) and a lot has changed since then. Feel free to fork it to work on it.
